name: Pipeline
on:
  push: 
    branches: 
      - main
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

  lint:
    needs: [check]
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - working-directory: /home/runner/work/practice-ci
        name: Install dependencies
        run: pnpm install
      - working-directory: /home/runner/work/practice-ci
        name: Run linter
        run: pnpm run eslint

  build:
    needs: [lint]
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - working-directory: /home/runner/work/practice-ci
        name: installing dependences
        run: pnpm install
      - working-directory: /home/runner/work/practice-ci
        name: build project
        run: pnpm run build
