name: Pipeline
on:
  push: 
    branches: 
      - main
jobs:
  lint:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run eslint

  build:
    needs: [lint]
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build
