name: Pipeline
on:
  push: 
    branches: 
      - main
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

  cache:
    needs: [check]
    runs-on: ubuntu-22.04
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
  
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        


  lint:
    name: Linter
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm install
      - run: pnpm run eslint

  build:
    needs: [lint]
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - run: pnpm install
      - run: pnpm run build
